version: '3.6'

services:
  dockersql.application.webapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5000:5000"
  
  sql.database:
    environment:
      - SA_PASSWORD=bliss123
      - ACCEPT_EULA=Y
    ports:
      - "1401:1433"
