version: '3.6'

services: 
  postgres:
    ports:
        - "5432:5432"
    container_name: 'postgresdb'
    image: postgres
    environment:
      POSTGRES_PASSWORD: "bliss123"
    networks:
      - postgres-compose-network
    volumes:
      - /home/renatogroffe/Desenvolvimento/Docker-Compose/PostgreSQL:/var/lib/postgresql/data
   
  teste-pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "api@api.com"
      PGADMIN_DEFAULT_PASSWORD: "123admin"
    ports:
      - "16543:80"
    depends_on:
      - postgres
    networks:
      - postgres-compose-network

networks: 
  postgres-compose-network:
    driver: bridge