version: '3.6'

services: 
  postgres:
    ports:
        - "5432:5432"
    container_name: 'postgresdb'
    image: postgres
    environment:
      POSTGRES_PASSWORD: "bliss123"
      POSTGRES_USER: "userapi"
      POSTGRES_DB: "blissdb"    
    
   
  teste-pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "api@api.com"
      PGADMIN_DEFAULT_PASSWORD: "123admin"
    ports:
      - "16543:80"
    depends_on:
      - postgres
    
